---
apiVersion: v1
kind: Pod
metadata:
  name: animals-lion-server-lb
  labels:
    client: lion
    app: web-server
spec:
  containers:
  - name: lino-app
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: animals-lion-server-service-lb
  labels:
    client: lion
spec:
  type: LoadBalancer
  selector:
    app: web-server
  ports:
  - port: 80
