---
apiVersion: v1
kind: Pod
metadata:
  name: animal-web-server
  namespace: animals
  labels:
    environment: production
    app: nginx
spec:
  containers:
  - name: animal-web-server
    image: nginx
    ports:
    - containerPort: 80
