---
apiVersion: v1
kind: Pod
metadata:
  name: animal-web-server
  labels:
    environment: production
spec:
  containers:
  - name: animal-web-server
    image: httpd
    ports:
    - containerPort: 80
